Add a flatpak backend
steven-omaha/pacdef pull request #20
Opened 2023-05-16 09:16 UTC by teackot

TODO:
- [x] install / uninstall
- [x] list
- [x] info
- [x] system-wide and per-user installation (config option)

2023-05-16 16:14 UTC, steven-omaha commented
FYI, the feature flags are normally used for backends that interact with some kind of library (Arch and Debian). As it seems you don't use a library to figure out the installed packages (as for Rust), you can remove the feature flag.

2023-05-16 16:31 UTC, teackot commented
Okay, I think I'm done

2023-05-16 16:36 UTC, steven-omaha commented
Please use `cargo fmt` and `cargo clippy` to fix all lints and formatting issues.

2023-05-16 16:42 UTC, steven-omaha requested changes
Nice work so far! I will try and think of a different solution for the runtime switches in `Backend`. Thank you!

2023-05-16 16:42 UTC, steven-omaha commented on README.md
move Flatpak up so that the 5 entries are in alphabetical order

2023-05-16 16:42 UTC, steven-omaha commented on crates/pacdef_core/src/backend/actual/mod.rs
alphabetical order please

2023-05-16 16:42 UTC, steven-omaha commented on crates/pacdef_core/src/backend/mod.rs
alphabetical order

2023-05-16 16:42 UTC, steven-omaha commented on crates/pacdef_core/src/backend/backend_trait.rs
I'm not sure about adding another method to the `Backend` trait. If that is the only solution, that's okay, but I will try and think if I can come up with a different solution. Leave this as it is for now.

2023-05-16 16:50 UTC, steven-omaha approved these changes

2023-05-16 16:53 UTC, teackot commented on crates/pacdef_core/src/backend/backend_trait.rs
I could implement custom install_packages(), remove_packages(), etc (like arch backend does) but it would be 90% copy of the default implementation,

2023-05-16 16:56 UTC, steven-omaha commented
Okay, so regarding the `get_switches_runtime()` in `Backend`, here's how I would prefer it.
- revert `pub trait Backend` to the state it was (remove the new method)
- in the methods where you need to differentiate between user and global, just overwrite the default implementation from the trait. That means in `impl Flatpak`, add your 
```rust
    fn get_switches_runtime(&self) -> Switches {
        todo!()
    }
```
and in `impl Backend for Flatpak` copy the default implementation from `Backend` for the four methods (info, remove, install, dependency), and then add your switches where necessary.

That came out a bit convoluted. Was that understandable?

2023-05-16 17:03 UTC, steven-omaha commented on crates/pacdef_core/src/backend/backend_trait.rs
Reason being I want to keep the trait as simple as possible since it should work for most cases as-is. If a specific backend requires something else, then it should take care of it itself. Otherwise over time the trait would accommodate every corner case. It's a choice between two suboptimal solutions.

2023-05-16 17:16 UTC, steven-omaha approved these changes
Great job!

2023-05-16 17:17 UTC, teackot commented
> That came out a bit convoluted. Was that understandable?

Got it

> and in `impl Backend for Flatpak` copy the default implementation from `Backend` for the four methods (info, remove, install, *dependency*), and then add your switches where necessary.

Didn't implement this one since flatpak doesn't support dependencies

2023-05-16 17:18 UTC, merged

2023-05-16 17:19 UTC, teackot commented
> Great job!

Thanks!

2023-05-16 17:29 UTC, steven-omaha commented
By the way, since you have now contributed to the code. Do you have feedback on how things are done in the code? Was the documentation sufficient? Is the codebase understandable?

2023-05-18 14:07 UTC, teackot commented
Documentation is definitely sufficient and the code is readable.

Though defining the constants in the backend file and implementing getters with a macro seems pretty hacky. Maybe you could declare them as `Backend` trait's associated items and define default getters in the trait, like this:

```rust
trait Backend {
    const SWITCHES_INSTALL: Switches;

    fn get_switches_install(&self) -> Vec<&'static str> {
        Self::SWITCHES_INSTALL.to_vec()
    }
}


impl Backend for Rust {
    const SWITCHES_INSTALL: Switches = &["install"];
}
```

Then, if we need to modify switches at runtime, we can implement a custom getter:

```rust
impl Backend for Flatpak {
    const SWITCHES_INSTALL: Switches = &["install"];

    fn get_switches_install(&self) -> Vec<&'static str> {
        if self.systemwide {
            Self::SWITCHES_INSTALL.to_vec()
        } else {
            [Self::SWITCHES_INSTALL, &["--user"]].concat()
        }
    }
}
```

2023-05-18 18:02 UTC, steven-omaha commented
> Though defining the constants in the backend file and implementing getters with a macro seems pretty hacky

I agree. 

> Maybe you could declare them as Backend trait's associated items and define default getters in the trait

I think I have tried something like this, but failed in implementing it. IIRC the compiler complained about `Backend`  and sizedness.  But my approach was somewhat different than yours. Maybe I'll try this out in the future.

Thanks.

2023-05-18 18:06 UTC, steven-omaha commented
Ah, now I remember.  Let's say I have 
```rust
pub trait Backend: Debug {
    const SWITCHES_INSTALL: Switches;
}
```

Then I get this error a bunch of times.

```
error[E0038]: the trait `Backend` cannot be made into an object
  --> crates/pacdef_core/src/backend/iter.rs:11:27
   |
11 |     fn next(&mut self) -> Option<Self::Item> {
   |                           ^^^^^^^^^^^^^^^^^^ `Backend` cannot be made into an object
   |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  --> crates/pacdef_core/src/backend/backend_trait.rs:18:11
   |
17 | pub trait Backend: Debug {
   |           ------- this trait cannot be made into an object...
18 |     const SWITCHES_INSTALL: Switches;
   |           ^^^^^^^^^^^^^^^^ ...because it contains this associated `const`
   = help: consider moving `SWITCHES_INSTALL` to another trait
```