More Refactors
steven-omaha/pacdef pull request #77
Opened 2024-04-24 16:01 UTC by ripytide

I don't think I've taken the opportunity to thank you for this amazing utility so far, so thank you!

In this PR:
- Refactor the confusing/bodgy consts backend macro to use a single
  `BackendInfo` struct
- Combine `supports_as_dependency()` and the `switches_dependency` into a single `Option` type as that is a better representation as it is an optional backend feature.
- Add more types like `Packages`, `Sections` for uniformity.
- Added a crate-private prelude and switches all imports to use a
  prelude glob import (excluding functions because it's nice to only be
  importing types)
- Refactored Backend section name in logging by implementing Display for
  `AnyBackend` that just prints the `section`

2024-04-24 17:55 UTC, steven-omaha requested changes
This is -- once again -- very good work. Most changes are small. 

If the docstring thingy fails the CI check, don't worry, I'll merge it regardless and add the docstrings soon.

There's two bugs:
- core.rs:448..456 are duplicated, one of the blocks needs to go
- there's a bug that I couldn't track down quickly, here's how to reproduce:

1. Have any Arch package with a repo prefix, like `core/linux`.
2. Run `cargo run -F arch -- p u`: it will show `linux` as unmanged
3. Run `cargo run -F arch -- p sy`: it will want to install `core/linux`.

That's not present in the previous commit, please check that out.

2024-04-24 17:55 UTC, steven-omaha commented on crates/pacdef/src/main.rs
> -    missing_docs
Keep the lints. If you'd rather not write the docstrings yourself I will take care of them.

2024-04-24 17:55 UTC, steven-omaha commented on crates/pacdef/src/lib.rs
> -    missing_docs
See main.rs

2024-04-24 17:55 UTC, steven-omaha commented on crates/pacdef/src/backend/backend_trait.rs
> +pub struct BackendInfo {
Make this a docstring

2024-04-24 17:55 UTC, steven-omaha commented on crates/pacdef/src/backend/mod.rs
> +pub struct ManagedBackend {
docstring

2024-04-24 17:55 UTC, steven-omaha commented on crates/pacdef/src/core.rs
> +            Err(error) => show_backend_query_error(&error, any_backend),
both code blocks are identical. I doubt that was the intention.

2024-04-24 17:56 UTC, steven-omaha commented
> I don't think I've taken the opportunity to thank you for this amazing utility so far, so thank you!

Thank you, very appreciated! I'm also learning so much from you right now, that's a great opportunity for me as well!

2024-04-25 10:27 UTC, steven-omaha commented
I think I found the issue. So far comparison of `Package`s was based on `PartialEq`. You introduced `ManagedBackend` which uses a `BTreeSet<Package>`, for which `BTreeSet<Package>::difference(...) where Package: Ord` is defined. So I think this uses `Ord`, which so far I have `derive`d in `src/grouping/package.rs:9`. If I understood this correctly you will need to `impl Ord for Package` to properly fix this bug.

2024-04-25 13:12 UTC, ripytide commented
Great catch! I've made the `Ord`/`PartialEq`... all consistent with each other and refactored some other stuff.

2024-04-27 07:27 UTC, merged

2024-04-27 07:27 UTC, steven-omaha commented
Thank you, merging